### ISSUE TITLE
Interested in collaboration?

### ISSUE THREAD

**Issue by alensiljak** [marek-g/rust-ledger-parser#15]
Hi, Marek!

Not sure if you've already noticed, I've recently raised a question in the plain-text accounting channel on Reddit, which got some interest in developing (a) Ledger(-like) in Rust. Obviously you're doing a lot in that regard already so I was wondering if you were interesting in pooling-in with others.
I've (very recently!) created an [organization](https://github.com/ledger-rs) to collect those interested in idea and try to focus the time and effort in a common goal. Please chip in if you're interested! Your parser is often mentioned in the discussions so far.
Cheers!

**Comment by marek-g** [comment]
Dnia środa, 21 grudnia 2022 21:52:51 CET Alen Šiljak pisze:
> Hi, Marek!
> 
> Not sure if you've already noticed, I've recently raised a question in the
> plain-text accounting channel on Reddit, which got some interest in
> developing (a) Ledger(-like) in Rust. Obviously you're doing a lot in that
> regard already so I was wondering if you were interesting in pooling-in
> with others. I've (very recently!) created an
> [organization](https://github.com/ledger-rs) to collect those interested in
> idea and try to focus the time and effort in a common goal. Please chip in
> if you're interested! Your parser is often mentioned in the discussions so
> far. Cheers!

Hi Alen! Let's talk via e-mail. Please send me PM to ***@***.*** 
Thanks!!

**Comment by marek-g** [comment]
... my email is in Cargo.toml.
