### ISSUE TITLE
Balance assertion support

### ISSUE THREAD

**Issue by huin** [marek-g/rust-ledger-parser#4]
Would it be reasonable to add [balance verifications](https://www.ledger-cli.org/3.0/doc/ledger3.html#Balance-verification) to `Posting`s and the parser? A downside would be that this would likely require a major version bump due to the new (optional) field in `Posting`.

This is probably something that I can attempt to implement myself with a pull request if it seems like a reasonable feature to add.

**Comment by marek-g** [comment]
Yes, of course. If you need it. I'm open for pull requests.

P.S. I'm currently working on optional amounts on a separate branch.

**Comment by marek-g** [comment]
Now in master. With API change to support special value "0".

**Comment by huin** [comment]
Thanks :)
